//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BotLibrary.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date changed to.
        /// </summary>
        internal static string ChangeDate {
            get {
                return ResourceManager.GetString("ChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples of currency codes
        ///---------------------------
        ///AUD  | AZN  | BYN | CAD
        ///CHF   | CNY  | CZK  | DKK
        ///EUR   | GBP  | GEL   |  HUF
        ///ILS     | JPY   | KZT   | MDL
        ///NOK  | PLN  | SEK   | SGD
        ///TMT   | TRY  | UAH | USD
        ///UZS   | XAU |          |     
        ///---------------------------
        ///Enter this format &quot;Key- YOUR KEY CURRENCY&quot;.
        /// </summary>
        internal static string ChooseDateKey {
            get {
                return ResourceManager.GetString("ChooseDateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.I`m currency bot, click on my buttons).
        /// </summary>
        internal static string CreateBoard {
            get {
                return ResourceManager.GetString("CreateBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don`t know this comand.
        /// </summary>
        internal static string DefaultAnswer {
            get {
                return ResourceManager.GetString("DefaultAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the date for the currency for the last 4 years..
        /// </summary>
        internal static string EnterDateMessage {
            get {
                return ResourceManager.GetString("EnterDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I`m sorry. Input date is not valid . Currency data for the last 4 years.
        /// </summary>
        internal static string ErrorDate {
            get {
                return ResourceManager.GetString("ErrorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi!
        ///This bot can showing the exchange rate of foreince currency to UAH.
        ////Help - information about bot.
        ////EnterDate - click on it and input date for foreince currency .
        ////ShowCurrency - shows a collection of currencies that you can view..
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I`m so sorry. I don&apos;t understand anything except the text..
        /// </summary>
        internal static string TextNotNullReference {
            get {
                return ResourceManager.GetString("TextNotNullReference", resourceCulture);
            }
        }
    }
}
